-- extraction_log definition

CREATE TABLE extraction_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            state_code TEXT NOT NULL,
            county_code TEXT NOT NULL,
            product_name TEXT NOT NULL,
            zip_file_path TEXT NOT NULL,
            extraction_success BOOLEAN NOT NULL,
            extraction_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            extracted_files_count INTEGER DEFAULT 0,
            shapefiles_found TEXT,
            error_message TEXT,
            FOREIGN KEY (state_code) REFERENCES states (state_code),
            FOREIGN KEY (county_code) REFERENCES counties (county_code)
        );

CREATE INDEX idx_extraction_log_state ON extraction_log (state_code);


-- Sample data:
-- |id|state_code|county_code|product_name|zip_file_path|extraction_success|extraction_timestamp|extracted_files_count|shapefiles_found|error_message|
-- |--|--|--|--|--|--|--|--|--|--|
-- |211|01|01001|FRD_03150201_shapefiles_20140221|E:\FEMA_DOWNLOAD\01\01001\FRD_03150201_shapefiles_20140221.zip|1|2025-07-20 18:37:31|124|[{"filename": "Shapefiles/R_UDF_Losses_by_Building.shp", "type": "Shapefiles/R_UDF_Losses_by_Building", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/R_UDF_Losses_by_Parcel.shp", "type": "Shapefiles/R_UDF_Losses_by_Parcel", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/R_UDF_Losses_by_Point.shp", "type": "Shapefiles/R_UDF_Losses_by_Point", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_AOMI_Pt.shp", "type": "Shapefiles/S_AOMI_Pt", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_Carto_Ar.shp", "type": "Shapefiles/S_Carto_Ar", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_Carto_Ln.shp", "type": "Shapefiles/S_Carto_Ln", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_CenBlk_Ar.shp", "type": "Shapefiles/S_CenBlk_Ar", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_CSLF_Ar.shp", "type": "Shapefiles/S_CSLF_Ar", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_FRD_Pol_Ar.shp", "type": "Shapefiles/S_FRD_Pol_Ar", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_FRD_Proj_Ar.shp", "type": "Shapefiles/S_FRD_Proj_Ar", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_FRM_Callout_Ln.shp", "type": "Shapefiles/S_FRM_Callout_Ln", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_HUC_Ar.shp", "type": "Shapefiles/S_HUC_Ar", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "Shapefiles/S_UDF_Pt.shp", "type": "Shapefiles/S_UDF_Pt", "geometry": "UNKNOWN", "category": "OTHER"}]|NULL|
-- |212|01|01003|FRD_01003C_Shapefiles|E:\FEMA_DOWNLOAD\01\01003\FRD_01003C_Shapefiles.zip|1|2025-07-20 18:37:33|120|[{"filename": "R_BuildingFootprints.shp", "type": "R_BuildingFootprints", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "R_Parcels.shp", "type": "R_Parcels", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "R_UDF_by_Point.shp", "type": "R_UDF_by_Point", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "S_AOMI_Pt.shp", "type": "S_AOMI_Pt", "geometry": "POINT", "category": "SPATIAL"}, {"filename": "S_Carto_Ar.shp", "type": "S_Carto_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_Carto_Ln.shp", "type": "S_Carto_Ln", "geometry": "LINESTRING", "category": "SPATIAL"}, {"filename": "S_CenBlk_Ar.shp", "type": "S_CenBlk_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_CSLF_Ar.shp", "type": "S_CSLF_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_FRD_Pol_Ar.shp", "type": "S_FRD_Pol_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_FRD_Proj_Ar.shp", "type": "S_FRD_Proj_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_FRM_Callout.shp", "type": "S_FRM_Callout", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "S_HUC_Ar.shp", "type": "S_HUC_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_UDF_Pt.shp", "type": "S_UDF_Pt", "geometry": "POINT", "category": "SPATIAL"}]|NULL|
-- |213|01|01009|FRD_03160111_ShapeFiles|E:\FEMA_DOWNLOAD\01\01009\FRD_03160111_ShapeFiles.zip|1|2025-07-20 18:37:50|127|[{"filename": "R_BuildingFootprints.shp", "type": "R_BuildingFootprints", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "R_Parcels.shp", "type": "R_Parcels", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "S_AOMI_Pt.shp", "type": "S_AOMI_Pt", "geometry": "POINT", "category": "SPATIAL"}, {"filename": "S_Carto_Ar.shp", "type": "S_Carto_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_Carto_Ln.shp", "type": "S_Carto_Ln", "geometry": "LINESTRING", "category": "SPATIAL"}, {"filename": "S_CenBlk_Ar.shp", "type": "S_CenBlk_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_Cr_Fac_Pt.shp", "type": "S_Cr_Fac_Pt", "geometry": "UNKNOWN", "category": "OTHER"}, {"filename": "S_CSLF_Ar.shp", "type": "S_CSLF_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_FRD_Pol_Ar.shp", "type": "S_FRD_Pol_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_FRD_Proj_Ar.shp", "type": "S_FRD_Proj_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_HUC_Ar.shp", "type": "S_HUC_Ar", "geometry": "POLYGON", "category": "SPATIAL"}, {"filename": "S_UDF_Pt.shp", "type": "S_UDF_Pt", "geometry": "POINT", "category": "SPATIAL"}]|NULL|
